(() => {
'use strict';
const cfg=window.LUNAVISUAL_CONFIG||{},$=id=>document.getElementById(id);let sb,role='user';
const status=(m,b=false)=>{const e=$('settingsStatus');if(e){e.textContent=m;e.className=`status ${b?'bad':'ok'}`}};
const dtLocal=v=>{if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return'';const z=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`};
async function init(){sb=window.LunaVisualSupabase||window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'lunavisual-auth-v2'}});window.LunaVisualSupabase=sb;const {data:{session}}=await sb.auth.getSession();if(!session){location.href='profile.html?next=settings.html';return}const rr=await sb.rpc('current_lunavisual_role');if(rr.error)throw rr.error;role=rr.data||'user';if(!['admin','super_admin'].includes(role)){$('guardStatus').innerHTML='<strong>Доступ запрещён</strong><div class="muted">Настройки доступны только администраторам.</div>';return}$('roleBadge').textContent=role==='super_admin'?'Глава / Super Admin':'Admin';$('guardStatus').classList.add('hidden');$('settingsContent').classList.remove('hidden');$('settingsForm').addEventListener('submit',save);$('reloadBtn').onclick=load;$('restartKeysBtn').onclick=restartKeys;await load()}
async function load(){status('Загрузка…');const {data,error}=await sb.from('site_settings').select('*').eq('id',1).single();if(error)throw error;const map={launcherUrl:'launcher_url',price7:'price_7',price30:'price_30',price90:'price_90',priceLifetime:'price_lifetime',alphaPrice:'alpha_price',discountPercent:'discount_percent',discountLabel:'discount_label',supportEmail:'support_email',telegramUrl:'telegram_url',discordUrl:'discord_url',funpayUrl:'funpay_url',keySystemMessage:'key_system_message'};for(const [id,k] of Object.entries(map))if($(id))$(id).value=data[k]??'';$('discountUntil').value=dtLocal(data.discount_until);for(const [id,k] of Object.entries({discountEnabled:'discount_enabled',keySystemEnabled:'key_system_enabled',alphaEnabled:'alpha_enabled',modelsEnabled:'models_enabled',creatorProgramEnabled:'creator_program_enabled',newsEnabled:'news_enabled',purchasesEnabled:'purchases_enabled',launcherLoginEnabled:'launcher_login_enabled',launcherMainMenuEnabled:'launcher_main_menu_enabled',launcherCosmeticsEnabled:'launcher_cosmetics_enabled',launcherSocialEnabled:'launcher_social_enabled'}))if($(id))$(id).checked=!!data[k];$('keyEpoch').textContent=`Версия системы: ${data.key_system_epoch||1}`;status('Настройки загружены.')}
async function save(e){e.preventDefault();$('saveBtn').disabled=true;status('Сохранение…');try{const patch={launcher_url:$('launcherUrl').value.trim(),price_7:Number($('price7').value||0),price_30:Number($('price30').value||0),price_90:Number($('price90').value||0),price_lifetime:Number($('priceLifetime').value||0),alpha_price:Number($('alphaPrice').value||0),discount_enabled:$('discountEnabled').checked,discount_percent:Number($('discountPercent').value||0),discount_label:$('discountLabel').value.trim()||'Скидка',discount_until:$('discountUntil').value?new Date($('discountUntil').value).toISOString():'',support_email:$('supportEmail').value.trim(),telegram_url:$('telegramUrl').value.trim(),discord_url:$('discordUrl').value.trim(),funpay_url:$('funpayUrl').value.trim(),key_system_enabled:$('keySystemEnabled').checked,key_system_message:$('keySystemMessage').value.trim(),alpha_enabled:$('alphaEnabled').checked,models_enabled:$('modelsEnabled').checked,creator_program_enabled:$('creatorProgramEnabled').checked,news_enabled:$('newsEnabled').checked,purchases_enabled:$('purchasesEnabled').checked,launcher_login_enabled:$('launcherLoginEnabled').checked,launcher_main_menu_enabled:$('launcherMainMenuEnabled').checked,launcher_cosmetics_enabled:$('launcherCosmeticsEnabled').checked,launcher_social_enabled:$('launcherSocialEnabled').checked};const {data,error}=await sb.rpc('admin_update_lunavisual_settings',{p_patch:patch});if(error)throw error;window.applyLunaVisualPublicSettings?.(data);status('Настройки сохранены.');await load()}catch(err){status(`Ошибка: ${err.message}`,true)}finally{$('saveBtn').disabled=false}}
async function restartKeys(){if(!confirm('Перезапустить систему ключей и сбросить временные лимиты активации? Ключи не удаляются.'))return;const {data,error}=await sb.rpc('admin_restart_lunavisual_key_system');if(error){status(error.message,true);return}$('keyEpoch').textContent=`Версия системы: ${data}`;status('Система ключей перезапущена. Ключи и активации сохранены.')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>init().catch(e=>status(e.message,true)));else init().catch(e=>status(e.message,true));
})();